# Exercícios - Salarios de São Francisco

Bem-vindo a um exercício rápido para você praticar suas habilidades de pandas! Vamos usar o [Dataset SF Salaries Dataset](https://www.kaggle.com/kaggle/sf-salaries) da Kaggle! Basta acompanhar e completar as tarefas descritas em negrito abaixo. As tarefas se tornarão cada vez mais difíceis.

**Importe o pandas como pd.**

In [1]:
import pandas as pd

**Leia o arquivo Salaries.csv como um DataFrame chamado "sal".**

In [2]:
sal = pd.read_csv('Salaries.csv')

**Verifique o "head" do DataFrame.**

In [3]:
# Não rode essa linha de código para não perder o resultado de exemplo
sal.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011.0,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011.0,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011.0,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011.0,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011.0,NaN,San Francisco,NaN

**Use o método .info () para descobrir quantas entradas existem.**

In [4]:
sal.info()

<class 'pandas.DataFrame'>
RangeIndex: 78778 entries, 0 to 78777
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Id                78778 non-null  int64
 1   EmployeeName      78778 non-null  str
 2   JobTitle          78778 non-null  str
 3   BasePay           78777 non-null  float64
 4   OvertimePay       78777 non-null  float64
 5   OtherPay          78777 non-null  float64
 6   Benefits          42618 non-null  float64
 7   TotalPay          78777 non-null  float64
 8   TotalPayBenefits  78777 non-null  float64
 9   Year              78777 non-null  float64
 10  Notes             0 non-null      float64
 11  Agency            78777 non-null  str
 12  Status            0 non-null      float64
dtypes: float64(9), int64(1), str(3)
memory usage: 11.3 MB

In [5]:
# Não rode essa linha de código para não perder o resultado de exemplo

**Qual é o "BasePay" médio?**

In [6]:
sal['BasePay'].mean()

np.float64(69878.0839363012)

In [7]:
# Não rode essa linha de código para não perder o resultado de exemplo

**Qual é a maior quantidade de "OvertimePay" no conjunto de dados?**

In [8]:
sal['OvertimePay'].max()

np.float64(245131.88)

In [9]:
# Não rode essa linha de código para não perder o resultado de exemplo

**Qual é o cargo de JOSEPH DRISCOLL? Nota: use todas as maiúsculas, caso contrário você pode obter uma resposta que não coincida (há também um Joseph Driscoll com minúsculas).**

In [10]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: str

In [11]:
sal[sal['EmployeeName'] == 'Joseph Driscoll']

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
36198,36199,Joseph Driscoll,"Captain, Fire Suppression",145658.98,114513.29,28743.36,42919.16,288915.63,331834.79,2012.0,NaN,San Francisco,NaN

In [12]:
# Não rode essa linha de código para não perder o resultado de exemplo

**Quanto JOSEPH DRISCOLL ganha (incluindo benefícios)?**

In [13]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

In [14]:
# Não rode essa linha de código para não perder o resultado de exemplo

**Qual o nome da pessoa mais bem paga (incluindo benefícios)?**

In [15]:
sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].max()]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011.0,NaN,San Francisco,NaN

In [16]:
# Não rode essa linha de código para não perder o resultado de exemplo

**Qual o nome da pessoa paga mais baixa (incluindo benefícios)? Você percebe algo estranho sobre o quanto ele ou ela é paga?**

In [17]:
sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].min()]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
36156,36157,PAULETTE ADAMS,"STATIONARY ENGINEER, WATER TREATMENT PLANT",0.0,0.0,0.0,NaN,0.0,0.0,2011.0,NaN,San Francisco,NaN
36157,36158,KAUKAB MOHSIN,TRANSIT OPERATOR,0.0,0.0,0.0,NaN,0.0,0.0,2011.0,NaN,San Francisco,NaN
36158,36159,JOSEPHINE MCCREARY,MANAGER IV,0.0,0.0,0.0,NaN,0.0,0.0,2011.0,NaN,San Francisco,NaN

In [18]:
# Não rode essa linha de código para não perder o resultado de exemplo

**Qual foi a média (média) BasePay de todos os funcionários por ano? (2011-2014)?**

In [19]:
sal.groupby('Year')['BasePay'].mean()

Year
2011.0     63595.956517
2012.0     65436.406857
2013.0    136600.254962
Name: BasePay, dtype: float64

**Quantos títulos de trabalho únicos existem?**

In [20]:
sal['JobTitle'].nunique()

2097

In [21]:
# Não rode essa linha de código para não perder o resultado de exemplo

**Quais são os 5 principais empregos mais comuns?**

In [22]:
sal['JobTitle'].value_counts().head()

JobTitle
TRANSIT OPERATOR    2388
Transit Operator    2269
Registered Nurse    1788
Special Nurse       1468
Police Officer 3    1423
Name: count, dtype: int64

In [23]:
# Não rode essa linha de código para não perder o resultado de exemplo

**Quantos Títulos de Trabalho foram representados por apenas uma pessoa em 2013? (Por exemplo, títulos de trabalho com apenas uma ocorrência em 2013?)**

In [24]:
sal_2013 = sal[sal['Year'] == 2013]
titles_2013 = sal_2013['JobTitle'].value_counts().reset_index()
sum(titles_2013['count'] == 1)

105

In [25]:
# Não rode essa linha de código para não perder o resultado de exemplo

**BONUS - Quantas pessoas têm a palavra Chefe em seu cargo?**

In [26]:
sum(sal['JobTitle'].apply(lambda x : 'CHIEF' in x.upper()))

437

In [27]:
sum(sal['JobTitle'].apply(lambda x : 'chief' in x.lower()))

437

In [28]:
# Não rode essa linha de código para não perder o resultado de exemplo